### PR TITLE
Return Dummy variables if stl can't be computed

### PR DESCRIPTION
**Pull request by Someone894**
When this package is used with the M4Metalearning-Package sometimes the stl-features of a time-series can't be computed, which leads to the whole system failing. So I added a dummy-stl return in case stl can't be computed.

I also added some missing brackets and fixed a missing bracket in compengine.R.

### CODE REVIEW

**Comment by robjhyndman** [comment]
Please provide a reproducible example where stl features fail.

**Comment by Someone894** [comment]
`forecast::mstl(ts(rep(1,24),frequency = 12))`
This is a minimal example of a not working timesieres.
Of course it can't work since it is too short, I know this very well.
But the sad reality is that such time series do exist and they have to be dealt with too.
Adding zeros in this case seemed to be the best option.

**Comment by robjhyndman** [comment]
A much better solution would be to use STL to estimate the trend only, then most of the features can still be computed. Now implemented in https://github.com/robjhyndman/tsfeatures/commit/cf67da4c73a2fa055a14d0701198de31cf9a9f08

**Comment by robjhyndman** [comment]
For future reference:

- NAs would be a better option to return when a feature can't be computed. Returning 0 suggests meaningful information when there isn't any.
- When doing a pull request, please make the smallest possible changes. Almost all of the changes proposed were styling code.
- When doing a pull request, please don't add package dependencies unless absolutely necessary. The use of

**Pull request closed without merging**
